# Generated by Django 6.0.6 on 2026-06-24 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='asientos',
            field=models.CharField(default='', max_length=255),
        ),
    ]
